project_id = "vkllrotescxmqwogfamo"

[functions.chat-support]
verify_jwt = true

[functions.companies-house]
verify_jwt = true

[functions.send-dividify-email]
verify_jwt = true

[functions.send-boardpack-email]
verify_jwt = true

[functions.feature-request]
verify_jwt = true
